### ISSUE TITLE
File not found: ... docs/_data/sidebars/home_sidebar.yml

### ISSUE THREAD

**Issue by chho-work** [pete88b/nbdev_colab_helper#3]
Hi, 
First of all, many thanks for providing this great tutorial and tools to access nbdev from Colab!  Great work!

I ran into a "file not found...home_sidebar.yml" error after following steps in your tutorial(https://pete88b.github.io/nbdev_colab_helper/tutorial.html):

1) Setup repo -> ok
2) Edit settings.ini -> ok
3) Edit 00_core.ipynb -> ok
4) Build lib -> ok
5) Edit index.ipynb -> changed few words and saved
6) Build docs -> error appeared in this section of your tutorial
When returning to your colab helper notebook and ran:

from nbdev.cli import nbdev_build_docs
nbdev_build_docs()

![Screenshot from 2021-01-20 16-33-26](https://user-images.githubusercontent.com/58581036/105148597-89534300-5b3d-11eb-857f-ecfd2d34284c.png)

I searched for "home_sidebar.yml" file in both my github repo and cloned repo in google drive, but couldn't find it.  This was a strange problem because I've used nbdev Colab previously(partially to build lib only and not docs), but didn't find this error. 

Please let me know what I am doing wrong!  Many thanks again!

Very best,

**Comment by pete88b** [comment]
It looks like updates to nbdev mean that the template project no longer needs `_data` etc in the docs folder. 

So [nbdev_template](https://github.com/fastai/nbdev_template) has been updated but ... nbdev_colab_helper is pinned to an [older version of nbdev](https://pypi.org/project/nbdev/1.0.14/) (Released: Sep 8, 2020).

You might be able to fix your project by copying missing files/folders from [this template](https://github.com/pete88b/nbdev_template) - this is my fork of nbdev_template (as of Apr 2020).

Or it might be better to start a new project from [this template](https://github.com/pete88b/nbdev_template).

Hope this helps ... I've not had time to try any of this out yet

**Comment by chho-work** [comment]
Thanks!  Starting a new project with [this template](https://github.com/pete88b/nbdev_template) worked!
